<div class="hedtop"></div>
<div class="portfolio-parlex" id="jadwal">
    <div class="exp-back">
        <div class="w-container">
          <div class="wrap">
              <div class="portfolio">
                <h3 class="experinc-box-h3" align="center">Tentang Perusahaan</h3>
                 
                <div class="container demo-1" style="color:#fffffff;">
                  <p style="text-align: justify;">WIKA dibentuk dari proses nasionalisasi perusahaan Belanda bernama Naamloze Vennotschap Technische Handel Maatschappij en Bouwbedijf Vis en Co. atau NV Vis en Co. Berdasarkan Peraturan Pemerintah No. 2 tahun 1960 dan Surat Keputusan Menteri Pekerjaan Umum dan Tenaga Listrik (PUTL) No. 5 tanggal 11 Maret 1960, dengan nama Perusahaan Negara Bangunan Widjaja Karja. Kegiatan usaha WIKA pada saat itu adalah pekerjaan instalasi listrik dan pipa air. Pada awal dasawarsa 1960-an, WIKA turut berperan serta dalam proyek pembangunan Gelanggang Olah Raga Bung Karno dalam rangka penyelenggaraan Games of the New Emerging Forces (GANEFO) dan Asian Games ke-4 di Jakarta.</p>
        <p style="text-align: justify;">Seiring berjalannya waktu, berbagai tahap pengembangan kerap kali dilakukan untuk terus tumbuh serta menjadi bagian dari pengabdian WIKA bagi perkembangan bangsa melalui jasa-jasa konstruksi yang tersebar di berbagai penjuru negeri.</p>
        <p style="text-align: justify;">Perkembangan signifikan pertama adalah di tahun 1972, dimana pada saat itu nama Perusahaan Negara Bangunan Widjaja Karja berubah menjadi PT Wijaya Karya. WIKA kemudian berkembang menjadi sebuah kontraktor konstruksi dengan menangani berbagai proyek penting seperti pemasangan jaringan listrik di Asahan dan proyek irigasi Jatiluhur.</p>
        <p style="text-align: justify;">Satu dekade kemudian, pada tahun 1982, WIKA melakukan perluasan divisi dengan dibentuknya beberapa divisi baru, yaitu Divisi Sipil Umum, Divisi Bangunan Gedung, Divisi Sarana Papan, Divisi Produk Beton dan Metal, Divisi Konstruksi Industri, Divisi Energy, dan Divisi Perdagangan. Proyek yang ditangani saat itu diantaranya adalah Gedung LIPI, Gedung Bukopin, dan Proyek Bangunan dan Irigasi. Selain itu, semakin berkembangnya anak-anak perusahaan di sektor industri konstruksi membuat WIKA menjadi perusahaan infrastruktur yang terintegrasi dan bersinergi.</p>
        <p style="text-align: justify;">Keterampilan para personel WIKA dalam industri konstruksi telah mendorong Perseroan untuk memperdalam berbagai bidang yang digelutinya dengan mengembangkan beberapa anak perusahaan guna dapat berdiri sendiri sebagai usaha yang spesialis dalam menciptakan produknya masing-masing. Pada tahun 1997, WIKA mendirikan anak perusahaannya yang pertama, yaitu PT Wijaya Karya Beton, mencerminkan pesatnya perkembangan Divisi Produk Beton WIKA saat itu.</p>
        <p style="text-align: justify;">Kegiatan PT Wijaya Karya Beton saat itu diantaranya adalah pengadaan bantalan jalan rel kereta api untuk pembangunan jalur double-track Manggarai, Jakarta, dan pembangunan PLTGU Grati serta Jembatan Cable Stayed Barelang di Batam. Langkah PT Wijaya Karya Beton kemudian diikuti dengan pendirian PT Wijaya Karya Realty pada tahun 2000 sebagai pengembangan Divisi Realty. Pada tahun yang sama didirikan pula PT Wijaya Karya Intrade sebagai pengembangan Divisi Industri dan Perdagangan.</p>
        <p style="text-align: justify;">Semakin berkembangnya Perseroan, semakin tinggi pula tingkat kepercayaan masyarakat terhadap kemampuan Perseroan. Hal ini tercermin dari keberhasilan WIKA melakukan penawaran saham perdana (Initial Public Offering/IPO) pada tanggal 27 Oktober 2007 di Bursa Efek Indonesia (saat itu bernama Bursa Efek Jakarta). Pada IPO tersebut, WIKA melepas 28,46 persen sahamnya ke publik, sehingga pemerintah Republik Indonesia memegang 68,42 persen saham, sedangkan sisanya dimiliki oleh masyarakat, termasuk karyawan, melalui Employee/Management Stock Option Program (E/MSOP), dan Employee Stock Allocation (ESA).</p>
        <p style="text-align: justify;">Sementara itu, langkah pengembangan Divisi menjadi anak perusahaan yang berdiri di atas kaki sendiri terus dilakukan. Pada tahun 2008 WIKA mendirikan anak perusahaan PT Wijaya Karya Gedung yang memiliki spesialisasi dalam bidang usaha pembangunan high rise building. WIKA juga mengakuisisi 70,08 persen saham PT Catur Insan Pertiwi yang bergerak di bidang mechanical-electrical. Kemudian nama PT Catur Insan Pertiwi dirubah menjadi PT Wijaya Karya Insan Pertiwi. Pada tahun 2009, bersama dengan PT Jasa Sarana dan RMI, mendirikan PT Wijaya Karya Jabar Power yang bergerak dalam pembangunan Pembangkit Listrik Tenaga Panas bumi (PLTP).</p>
        <p style="text-align: justify;">Di pertengahan tahun 2009, WIKA bersama perusahaan lain berhasil menyelesaikan Jembatan Suramadu, sebuah proyek prestisius yang menghubungkan pulau Jawa dengan pulau Madura. Kini proyek tersebut telah dirasakan manfaatnya oleh masyarakat luas.</p>
        <p style="text-align: justify;">Memasuki tahun 2010, WIKA berhadapan dengan lingkungan usaha yang berubah dengan tantangan lebih besar. Untuk itu, WIKA telah menyiapkan Visi baru, yaitu VISI 2020 untuk menjadi salah satu perusahaan EPC dan Investasi terintegrasi terbaik di Asia Tenggara. Visi ini diyakini dapat memberi arah ke segenap jajaran WIKA untuk mencapai pertumbuhan yang lebih optimal, sehat dan berkelanjutan.</p>
        <p style="text-align: justify;">Sepanjang tahun 2012, WIKA berhasil menuntaskan proyek power plant yang terdiri dari: Pembangkit Listrik Tenaga Gas Borang, 60MW, Pembangkit Listrik Tenaga Mesin Gas Rengat, 21MW, Pembangkit Listrik Tenaga Diesel Ambon, 34MW.</p>
        <p style="text-align: justify;">Pada tahun 2013 Perseroan mendirikan usaha patungan PT Prima Terminal Peti Kemas bersama PT Pelindo I (Persero) dan PT Hutama Karya (Persero), mengakuisisi saham PT Sarana Karya (Persero) (“SAKA”) yang sebelumnya dimiliki oleh Pemerintah Republik Indonesia, mendirikan usaha patungan PT WIKA Kobe dan PT WIKA Krakatau Beton melalui Entitas Anak WIKA Beton, dan melakukan buyback saham sebanyak 6.018.500 saham dengan harga perolehan rata-rata Rp1.706,77,-</p>
                </div>
              </div>
          </div>
        </div>
    </div>
</div>

